### PR TITLE
Add dhcp support

### PR DESCRIPTION
**Pull request by fnordfish**
open issue: The `restart_host_dns` action hook needs to get moved after provider specific actions (so that the host network had a chance to get configured).
see mitchellh/vagrant#8500

### CODE REVIEW

**Comment by mattiasb** [comment]
Would I be correct in saying that what we need is to use the new hooks provided in hashicorp/vagrant#10615 in [lib/vagrant-dns.rb:L41-L49](hashicorp/vagrant/pull/10615)?

And probably what we want to do is to not hook in to `machine_action_up` but to a new hook that we are certain will be triggered *after* network is configured?

I wonder what we should do with the `machine_action_reload` hook. If it works like I imagine it would it will be called when a machine is reconfigured but possibly *before* network is up again? I suppose one just needs to test.

Just checking what your thoughts here are. Sorry for pressing on about this, it's just that since I got bitten by vagrant-landrush/landrush#360 I need to find a new solution for or test environment at work.

**Comment by fnordfish** [comment]
@mattiasb I've updated this PR a bit. Would you mind giving it a try?

**Comment by mattiasb** [comment]
> @mattiasb I've updated this PR a bit. Would you mind giving it a try?

Omg, yes! I have a couple of really busy days though, so if I seem to have forgotten that's why. If I don't find time tomorrow though then early next week!

**Comment by fnordfish** [comment]
No hurry, take your time. Thanks a lot!

**Comment by mattiasb** [comment]
I got it working! :)
I had to do this to `Gemfile`:
```diff
@@ -13,11 +13,6 @@ group :plugins do
 end
 
 group :test, :development do
-  if ENV['TEST_VAGRANT_VERSION'] == 'HEAD'
-    gem 'vagrant', :git => 'https://github.com/hashicorp/vagrant', :branch => 'main'
-  else
-    gem 'vagrant', :git => 'https://github.com/hashicorp/vagrant', :tag => ENV['TEST_VAGRANT_VERSION']
-  end
   gem 'rubydns', '~> 2.0.0'
 end
```
(Fedora is on Ruby 3.2.1 which is too new for Vagrant apparently, they probably did some packaging magic).

... and then add this to my `Vagrantfile`:

```
  config.dns.ip = -> (vm, opts) do
    ip = nil
    vm.communicate.execute("hostname -I | cut -d ' ' -f 1") do |type, data|
      ip = data.strip if type == :stdout
    end
    ip
  end
```

But then after a couple restarts and stuff it indeed worked!

**Comment by fnordfish** [comment]
Great news!

That you had to remove the `vagrant` dependency is a bit weird, but it might indeed have something to do with the more modern ruby you used to build the gem. I assume you build the gem file via `rake build` and then used `vagrant plugin install` - is that right?

The manual `config.dns.ip` setup shouldn't be needed. If a DHCP network is detected, the default would essentially be:

```ruby
config.dns.ip = proc { |vm|
  vm.guest.capability(:read_ip_address).tap { |ip|
    if ip
      vm.ui.info "[vagrant-dns] Identified DHCP IP as '#{ip}'."
    else
      vm.ui.warn "[vagrant-dns] Could not identify DHCP IP."
    end
  }
}
```

Again, that is **if** a DHCP network is detected. If it cannot be detected, for whatever reason, you'll to declare it like you did, or copy'n'paste the default.
I probably need to make that more clear in the Readme. Also, if you got any suggestion how to make that easier from the perspective of an Vagrantfile-author, please let me know.

I'm not quite sure why the dns process hangs. Can you have a look into `~/.vagrant.d/tmp/dns/daemon/vagrant-dns.output` and try to manually `vagrant dns --stop|--start|--restart`. Maybe there's another/old process still running and the startup does not fail as expected. `pgrep -alf vagrant-dns` should give you a list.

**Comment by mattiasb** [comment]
> Great news!
> 
> That you had to remove the `vagrant` dependency is a bit weird, but it might indeed have 
> something to do with the more modern ruby you used to build the gem. I assume you build the 
> gem file via `rake build` and then used `vagrant plugin install` - is that right?

Yeah I believe that's the case. It's one of the quirks of living on the bleeding edge.

> The manual `config.dns.ip` setup shouldn't be needed. If a DHCP network is detected, the 
> default would essentially be:
> 
> ```ruby
> config.dns.ip = proc { |vm|
>   vm.guest.capability(:read_ip_address).tap { |ip|
>     if ip
>       vm.ui.info "[vagrant-dns] Identified DHCP IP as '#{ip}'."
>     else
>       vm.ui.warn "[vagrant-dns] Could not identify DHCP IP."
>     end
>   }
> }
> ```
> 
> Again, that is **if** a DHCP network is detected. If it cannot be detected, for whatever 
> reason, you'll to declare it like you did, or copy'n'paste the default. I probably need to 
> make that more clear in the Readme. 

I tried to understand what the code was doing when looking at this but I must admit I failed. I'd like to look into why DHCP isn't detected. Could you point me to where in the code that check is made?

> Also, if you got any suggestion how to make that easier from the perspective of an 
> Vagrantfile-author, please let me know.

Sure, I'll keep that in mind! If possible what one wants is zero configuration (except for setting the TLD and the IP/Port of the vagrant-dns process for example). I hope that's possible.

> I'm not quite sure why the dns process hangs. Can you have a look into `~/.vagrant.d/tmp/dns
> /daemon/vagrant-dns.output` and try to manually `vagrant dns --stop|--start|--restart`. Maybe > there's another/old process still running and the startup does not fail as expected. 
> `pgrep -alf vagrant-dns` should give you a list.

Yeah, I'll try to debug this!

Thanks!

**Comment by fnordfish** [comment]
The diff got quite messy b/c I did quite some whitespace changes :/
Anyways, here's the DHCP detection: https://github.com/BerlinVagrant/vagrant-dns/blob/a2917b1a78fa3919c77c9149d281914fa75b4dfb/lib/vagrant-dns/configurator.rb#L173-L177

It looks for any private or public network with type `dhcp`. I've tested using `config.vm.network :private_network, type: :dhcp`.

There are some quirks regarding `public_network` - they heavily depend on the provider. Eg. you cannot configure a static IP on VMware desktop. So it's essentially DHCP, but not marked as such.

Maybe I should change the detection to look for static IP configs, and if none is found fall back to "dhcp-mode".

**Comment by mattiasb** [comment]
> The diff got quite messy b/c I did quite some whitespace changes :/ Anyways, here's the DHCP detection:
> 
> https://github.com/BerlinVagrant/vagrant-dns/blob/a2917b1a78fa3919c77c9149d281914fa75b4dfb/lib/vagrant-dns/configurator.rb#L173-L177
> 
> It looks for any private or public network with type `dhcp`. I've tested using `config.vm.network :private_network, type: :dhcp`.

Ah gotcha, thanks!

> There are some quirks regarding `public_network` - they heavily depend on the provider. Eg. 
> you cannot configure a static IP on VMware desktop. So it's essentially DHCP, but not marked 
> as such.

That might be what's happening with `libvirt` with the user session. As an unprivileged user you're not allowed to set up your own network etc and hence if you don't configure anything what you get is DHCP. Maybe the code would work if I set the network to DHCP manually?

I will test that now.

> Maybe I should change the detection to look for static IP configs, and if none is found fall
> back to "dhcp-mode".

That sounds like a potential solution, and I saw that you did that now. I'll try out setting DHCP manually using the older code path and then if that works I'll see if the new code lets me avoid adding that config.

**Comment by mattiasb** [comment]
> > There are some quirks regarding `public_network` - they heavily depend on the provider. Eg.
> > you cannot configure a static IP on VMware desktop. So it's essentially DHCP, but not 
> > marked
> > as such.
> 
> That might be what's happening with `libvirt` with the user session. As an unprivileged user 
> you're not allowed to set up your own network etc and hence if you don't configure anything 
> what you get is DHCP. Maybe the code would work if I set the network to DHCP manually?
> 
> I will test that now.

I got it working with both:

```ruby
config.vm.network "private_network", type: "dhcp"
```
and
```ruby
      server.vm.network :public_network,
                        :dev => "virbr0",
                        :mode => "bridge",
                        :type => "bridge"
```

... and now when I test it actually works just fine with the default config (that is without setting up a network at all since it then defaults to dhcp).

I feel slightly gaslighted by Vagrant and libvirt right now to be honest but it sounds like the code you wrote initially works just fine!

I double checked `.vagrant/plugins/gems/3.1.3/gems/vagrant-dns-2.3.0/lib/vagrant-dns/configurator.rb` to make sure I had the old code and yeah:

```ruby
    private def has_dhcp_network?(opts)
      opts[:networks].any? { |(nw_type, nw_config)|
        nw_config[:type] == :dhcp && (nw_type == :private_network || nw_type == :public_network)
      }
```

> > Maybe I should change the detection to look for static IP configs, and if none is found 
> > fall back to "dhcp-mode".
> 
> That sounds like a potential solution, and I saw that you did that now. I'll try out setting 
> DHCP manually using the older code path and then if that works I'll see if the new code lets 
> me avoid adding that config.

I think you can revert those changes if you want to. With that said I'll test with them now as well so that you get an extra data point.

**Comment by mattiasb** [comment]
> Thanks for testing! I guess [the new "dhcp" detection](https://github.com/BerlinVagrant/vagrant-dns/blob/1e56a1e12543c70299ac9d6875b0eed3874c93c9/lib/vagrant-dns/configurator.rb#L172-L174) is simpler ("if there's no static IP configured, assume DHCP mode"), and I'd rather keep that.
 
Makes sense!

> Using the updated code, you should be able to remove the `config.dns.ip` config in your 
> Vagrantfile.

Yeah I did that during all the tests and it resolved my `mgmt.test` host just fine! Great job!

**Comment by mattiasb** [comment]
🙌🎉 🍾

**Pull request merged**
